package com.goodgamestudios.mafia.controller.clientCommands
{
   import com.goodgamestudios.basic.controller.BasicController;
   import com.goodgamestudios.basic.controller.BasicSmartfoxConstants;
   import com.goodgamestudios.basic.controller.clientCommands.BasicInitServerCommands;
   import com.goodgamestudios.basic.controller.commands.GCHCommand;
   import com.goodgamestudios.basic.controller.commands.GFLCommand;
   import com.goodgamestudios.mafia.constants.Constants_SFS;
   import com.goodgamestudios.mafia.controller.ProtobufController;
   import com.goodgamestudios.mafia.controller.commands.account.CreateAvatarCommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.AUCCommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.CAVCommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.GUACommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.GetPlayerBoosterCommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.IPLCommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.NOFCommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.OGACommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.OIOCommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.OUDCommand;
   import com.goodgamestudios.mafia.controller.commands.avatar.UATCommand;
   import com.goodgamestudios.mafia.controller.commands.booster.BuyMissionBoosterCommand;
   import com.goodgamestudios.mafia.controller.commands.booster.ShowMissionBoosterCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.ChangeCrestCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.ChangeFamilyMemberStatusCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.CreateFamilyCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.DonateFamilyCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.FamilyChangeBulletinBoardCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.FamilyGetBulletinBoardCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.FamilyMessageCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.GetAvailableFamilyCrestPartsCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.InitiateClanWarCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.InvitePlayerToFamilyCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.JoinFamilyCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.LookingForFamilyCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.ParticipateClanWarCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.ShowClanCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.ShowClanWarCommand;
   import com.goodgamestudios.mafia.controller.commands.clan.UpdateClanBonusCommand;
   import com.goodgamestudios.mafia.controller.commands.common.APDCommand;
   import com.goodgamestudios.mafia.controller.commands.common.CMT_Mafia_Command;
   import com.goodgamestudios.mafia.controller.commands.common.FDBCommand;
   import com.goodgamestudios.mafia.controller.commands.common.LCPCommand;
   import com.goodgamestudios.mafia.controller.commands.common.LFECommand;
   import com.goodgamestudios.mafia.controller.commands.common.LGNCommand;
   import com.goodgamestudios.mafia.controller.commands.common.LLPCommand;
   import com.goodgamestudios.mafia.controller.commands.common.LRECommand;
   import com.goodgamestudios.mafia.controller.commands.common.LSNCommand;
   import com.goodgamestudios.mafia.controller.commands.common.PNGCommand;
   import com.goodgamestudios.mafia.controller.commands.common.PPCCommand;
   import com.goodgamestudios.mafia.controller.commands.common.QTUCommand;
   import com.goodgamestudios.mafia.controller.commands.common.SGCCommand;
   import com.goodgamestudios.mafia.controller.commands.common.SOECommand;
   import com.goodgamestudios.mafia.controller.commands.common.VCKCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.PrepareDuelFightCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.SDUCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.SSUCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.STUCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.StartDuelFightCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.StartSurvivalFightCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.StartWantedFightCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.SurvivalStatusCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.TestFightCommand;
   import com.goodgamestudios.mafia.controller.commands.duel.VEFCommand;
   import com.goodgamestudios.mafia.controller.commands.email.EMCCommand;
   import com.goodgamestudios.mafia.controller.commands.email.EMVCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.AddArmamentCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.ChangeArmamentCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.ChangeInventoryCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.EquipArmamentCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.EquipFoodCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.EquipGearCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.GetArmamentPresetStatusCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.OpenContainerCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.SetActiveArmamentCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.UnequipArmamentCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.UnequipFoodCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.UnequipGearCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.UnlockArmamentCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.ViewArmamentCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.ViewFoodCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.ViewGearCommand;
   import com.goodgamestudios.mafia.controller.commands.equipment.ViewInventoryCommand;
   import com.goodgamestudios.mafia.controller.commands.events.SAECommand;
   import com.goodgamestudios.mafia.controller.commands.featurestatus.GetFeatureStatus;
   import com.goodgamestudios.mafia.controller.commands.fight.SelectCityFightItemCommand;
   import com.goodgamestudios.mafia.controller.commands.fight.ShowCityFightCommand;
   import com.goodgamestudios.mafia.controller.commands.fight.ShowCityFightItemsCommand;
   import com.goodgamestudios.mafia.controller.commands.fight.StartCityFightCommand;
   import com.goodgamestudios.mafia.controller.commands.friend.BPPCommand;
   import com.goodgamestudios.mafia.controller.commands.friend.GALCommand;
   import com.goodgamestudios.mafia.controller.commands.friend.SBSCommand;
   import com.goodgamestudios.mafia.controller.commands.friend.SFLCommand;
   import com.goodgamestudios.mafia.controller.commands.gang.DGACommand;
   import com.goodgamestudios.mafia.controller.commands.gang.HGACommand;
   import com.goodgamestudios.mafia.controller.commands.gang.SGACommand;
   import com.goodgamestudios.mafia.controller.commands.gang.SGSCommand;
   import com.goodgamestudios.mafia.controller.commands.gangwars.SDOCommand;
   import com.goodgamestudios.mafia.controller.commands.gangwars.ShowGangWarsCommand;
   import com.goodgamestudios.mafia.controller.commands.gangwars.StartGangwarFightCommand;
   import com.goodgamestudios.mafia.controller.commands.gangwars.UNDCommand;
   import com.goodgamestudios.mafia.controller.commands.item.UnlockInventoryCommand;
   import com.goodgamestudios.mafia.controller.commands.messages.DeleteMessageCommand;
   import com.goodgamestudios.mafia.controller.commands.messages.GetMessagesStatusCommand;
   import com.goodgamestudios.mafia.controller.commands.messages.ReadMessageCommand;
   import com.goodgamestudios.mafia.controller.commands.messages.SMSCommand;
   import com.goodgamestudios.mafia.controller.commands.messages.ShowNewsCommand;
   import com.goodgamestudios.mafia.controller.commands.misc.LoginWelcomeCommand;
   import com.goodgamestudios.mafia.controller.commands.misc.NewAchievementsCommand;
   import com.goodgamestudios.mafia.controller.commands.misc.PaymentInfoCommand;
   import com.goodgamestudios.mafia.controller.commands.misc.PlayerCurrencyCommand;
   import com.goodgamestudios.mafia.controller.commands.misc.PlayerProfileCommand;
   import com.goodgamestudios.mafia.controller.commands.mission.BENCommand;
   import com.goodgamestudios.mafia.controller.commands.mission.QuitMissionCommand;
   import com.goodgamestudios.mafia.controller.commands.mission.StartMissionCommand;
   import com.goodgamestudios.mafia.controller.commands.mission.ViewMissionCommand;
   import com.goodgamestudios.mafia.controller.commands.police.POBCommand;
   import com.goodgamestudios.mafia.controller.commands.police.PoliceBadgeConversionCommand;
   import com.goodgamestudios.mafia.controller.commands.police.PoliceEncounterCommand;
   import com.goodgamestudios.mafia.controller.commands.police.StartPoliceFightCommand;
   import com.goodgamestudios.mafia.controller.commands.quest.FinishQuestCommand;
   import com.goodgamestudios.mafia.controller.commands.quest.GetActiveQuestsCommand;
   import com.goodgamestudios.mafia.controller.commands.quest.PauseQuestCommand;
   import com.goodgamestudios.mafia.controller.commands.quest.StartQuestCommand;
   import com.goodgamestudios.mafia.controller.commands.quest.UpdateQuestCommand;
   import com.goodgamestudios.mafia.controller.commands.quest.ViewQuestBookCommand;
   import com.goodgamestudios.mafia.controller.commands.ranking.SRTCommand;
   import com.goodgamestudios.mafia.controller.commands.ranking.SearchRankingCommand;
   import com.goodgamestudios.mafia.controller.commands.shop.BuyItemCommand;
   import com.goodgamestudios.mafia.controller.commands.shop.ClearSafeCommand;
   import com.goodgamestudios.mafia.controller.commands.shop.IRTCommand;
   import com.goodgamestudios.mafia.controller.commands.shop.OrderItemsCommand;
   import com.goodgamestudios.mafia.controller.commands.shop.SaveItemCommand;
   import com.goodgamestudios.mafia.controller.commands.shop.SellItemCommand;
   import com.goodgamestudios.mafia.controller.commands.shop.ViewItemsCommand;
   import com.goodgamestudios.mafia.controller.commands.slotmachine.SSMCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.CityEventStateCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.LuckyDevilCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.SpecialCalendarCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.SpecialWantedCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.TournamentCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.calendar.UnlockNextDayCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.city.CityEventProgressCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.city.PayCityEventMissionCooldownCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.city.QuitCityEventMissionCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.city.ShowCityEventOpponentCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.city.StartCityEventFightCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.city.StartCityEventMissionCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.luckydevil.BuyCardsCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.luckydevil.TurnCardCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.tournament.HealTournamentPlayerCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.tournament.RegisterForTournamentCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.tournament.SearchTournamentPlayerCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.tournament.ShowRemainingTournamentPlayersCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.tournament.ShowTournamentFinalsCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.tournament.ShowTournamentInfoCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.tournament.TournamentRoundReportsCommand;
   import com.goodgamestudios.mafia.controller.commands.specialevent.tournament.ViewTournamentFightCommand;
   import com.goodgamestudios.mafia.controller.commands.travels.QuitTravelFlightCommand;
   import com.goodgamestudios.mafia.controller.commands.travels.ShowTravelPossibilitiesCommand;
   import com.goodgamestudios.mafia.controller.commands.travels.StartTravelFlightCommand;
   import com.goodgamestudios.mafia.controller.commands.work.GoWorkingCommand;
   import com.goodgamestudios.mafia.controller.commands.work.StopWorkingCommand;
   import com.goodgamestudios.mafia.controller.commands.work.ViewWorkCommand;
   import flash.utils.Dictionary;
   
   public class MafiaInitServerCommandsCommand extends BasicInitServerCommands
   {
       
      
      public function MafiaInitServerCommandsCommand()
      {
         super();
      }
      
      override public function execute(param1:Object = null) : void
      {
         var _loc2_:Dictionary = BasicController.commandDict;
         _loc2_[BasicSmartfoxConstants.S2C_CASH_HASH] = new GCHCommand();
         _loc2_[BasicSmartfoxConstants.S2C_GET_FORUM_LOGIN_DATA] = new GFLCommand();
         _loc2_[BasicSmartfoxConstants.S2C_REGISTER] = new LRECommand();
         _loc2_[BasicSmartfoxConstants.S2C_LOGIN] = new LGNCommand();
         _loc2_[BasicSmartfoxConstants.S2C_LOST_PASSWORD] = new LLPCommand();
         _loc2_[BasicSmartfoxConstants.S2C_CHANGE_PASSWORD] = new LCPCommand();
         _loc2_[BasicSmartfoxConstants.S2C_VERSION_CHECK] = new VCKCommand();
         _loc2_[BasicSmartfoxConstants.S2C_SPECIAL_OFFER_EVENT] = new SOECommand();
         _loc2_[BasicSmartfoxConstants.S2C_PAYMENTSHOP_PRICE_CHANGE] = new PPCCommand();
         _loc2_[BasicSmartfoxConstants.S2C_COMA_TEASER] = new CMT_Mafia_Command();
         _loc2_[Constants_SFS.S2C_EMAIL_VERIFICATION] = new EMVCommand();
         _loc2_[Constants_SFS.S2C_EMAIL_CONFIRMED] = new EMCCommand();
         _loc2_[Constants_SFS.S2C_LOGIN_SET_NAME] = new LSNCommand();
         _loc2_[Constants_SFS.S2C_GET_ALLPLAYERDATA] = new APDCommand();
         _loc2_[Constants_SFS.S2C_LOGIN_FEATURES] = new LFECommand();
         _loc2_[Constants_SFS.S2C_PING] = new PNGCommand();
         _loc2_[Constants_SFS.S2C_FEEDBACK] = new FDBCommand();
         _loc2_[Constants_SFS.S2C_QUIT_TUTORIAL] = new QTUCommand();
         _loc2_[Constants_SFS.S2C_AVATAR_USERDATA] = new OUDCommand();
         _loc2_[Constants_SFS.S2C_AVATAR_ACHIEVMENTS] = new OGACommand();
         _loc2_[Constants_SFS.S2C_GET_ATTRIBUTE_UPGRADE_COSTS] = new AUCCommand();
         _loc2_[Constants_SFS.S2C_UPGRADE_ATTRIBUTE] = new UATCommand();
         _loc2_[Constants_SFS.S2C_PLAYER_INFO] = new OIOCommand();
         _loc2_[Constants_SFS.S2C_BUY_ENERGY] = new BENCommand();
         _loc2_[Constants_SFS.S2C_ITEM_RESPONSE_TIMEOUT] = new IRTCommand();
         _loc2_[Constants_SFS.S2C_SHOW_TOP_RANKING] = new SRTCommand();
         _loc2_[Constants_SFS.S2C_SHOW_DUEL] = new SDUCommand();
         _loc2_[Constants_SFS.S2C_VIEW_WANTED_FIGHT] = new VEFCommand();
         _loc2_[Constants_SFS.S2C_SEND_MSG] = new SMSCommand();
         _loc2_[Constants_SFS.S2C_IGNORE_PLAYER] = new IPLCommand();
         _loc2_[Constants_SFS.S2C_SHOW_GANGWAR_OPPONENTS] = new SDOCommand();
         _loc2_[Constants_SFS.S2C_UNLOCK_NEXT_GANGWAR] = new UNDCommand();
         _loc2_[Constants_SFS.S2C_NOTIFICATION] = new NOFCommand();
         _loc2_[Constants_SFS.S2C_ADDFRIEND_LINK] = new GALCommand();
         _loc2_[Constants_SFS.S2C_SEND_FRIEND_LINK] = new SFLCommand();
         _loc2_[Constants_SFS.S2C_SOCIAL_BUDDIES] = new SBSCommand();
         _loc2_[Constants_SFS.S2C_GET_BUDDY_PLAYER_PROFILE] = new BPPCommand();
         _loc2_[Constants_SFS.S2C_CHANGE_AVATAR] = new CAVCommand();
         _loc2_[Constants_SFS.S2C_START_SLOTMACHINE] = new SSMCommand();
         _loc2_[Constants_SFS.S2C_SHOW_ACTIVE_EVENTS] = new SAECommand();
         _loc2_[Constants_SFS.S2C_GET_UNLOCKED_ASSETS] = new GUACommand();
         _loc2_[Constants_SFS.S2C_SET_GOLD_CONSTANTS] = new SGCCommand();
         _loc2_[Constants_SFS.S2C_SHOW_SURVIVAL_COOLDOWN] = new SSUCommand();
         _loc2_[Constants_SFS.S2C_START_SURVIVAL] = new STUCommand();
         _loc2_[Constants_SFS.S2C_SHOW_GANG_SHOP] = new SGSCommand();
         _loc2_[Constants_SFS.S2C_SHOW_GANG] = new SGACommand();
         _loc2_[Constants_SFS.S2C_FIRE_GANGMEMBER] = new DGACommand();
         _loc2_[Constants_SFS.S2C_HIRE_GANGMEMBER] = new HGACommand();
         _loc2_[Constants_SFS.S2C_POST_BAIL] = new POBCommand();
         var _loc3_:Dictionary = ProtobufController.getInstance().commandDict;
         _loc3_[Constants_SFS.PROTOBUF_TEST_FIGHT] = new TestFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_LOGIN_WELCOME] = new LoginWelcomeCommand();
         _loc3_[Constants_SFS.PROTOBUF_PREPARE_DUEL] = new PrepareDuelFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_DUEL] = new StartDuelFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_WANTED_FIGHT] = new StartWantedFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_PLAYER_PROFILE] = new PlayerProfileCommand();
         _loc3_[Constants_SFS.PROTOBUF_SURVIVAL_STATUS] = new SurvivalStatusCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_GANGWAR_FIGHT] = new StartGangwarFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_NEW_ACHIEVEMENTS] = new NewAchievementsCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_CLAN_WAR_FIGHT] = new ShowClanWarCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_WANTED_FIGHT] = new StartWantedFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_SURVIVAL_FIGHT] = new StartSurvivalFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_CREATE_AVATAR] = new CreateAvatarCommand();
         _loc3_[Constants_SFS.PROTOBUF_READ_MSG] = new ReadMessageCommand();
         _loc3_[Constants_SFS.PROTOBUF_DELETE_MSG] = new DeleteMessageCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_NEWS] = new ShowNewsCommand();
         _loc3_[Constants_SFS.PROTOBUF_GET_MSGS_STATUS] = new GetMessagesStatusCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_MISSION] = new StartMissionCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_MISSIONS] = new ViewMissionCommand();
         _loc3_[Constants_SFS.PROTOBUF_QUIT_MISSION] = new QuitMissionCommand();
         _loc3_[Constants_SFS.PROTOBUF_GO_WORKING] = new GoWorkingCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_WORK] = new ViewWorkCommand();
         _loc3_[Constants_SFS.PROTOBUF_STOP_WORKING] = new StopWorkingCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_ARMAMENT] = new ViewArmamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_FOOD] = new ViewFoodCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_GEAR] = new ViewGearCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_INVENTORY] = new ViewInventoryCommand();
         _loc3_[Constants_SFS.PROTOBUF_CHANGE_ARMAMENT] = new ChangeArmamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_CHANGE_INVENTORY] = new ChangeInventoryCommand();
         _loc3_[Constants_SFS.PROTOBUF_EQUIP_ARMAMENT] = new EquipArmamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_EQUIP_FOOD] = new EquipFoodCommand();
         _loc3_[Constants_SFS.PROTOBUF_EQUIP_GEAR] = new EquipGearCommand();
         _loc3_[Constants_SFS.PROTOBUF_UNEQUIP_ARMAMENT] = new UnequipArmamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_UNEQUIP_FOOD] = new UnequipFoodCommand();
         _loc3_[Constants_SFS.PROTOBUF_UNEQUIP_GEAR] = new UnequipGearCommand();
         _loc3_[Constants_SFS.PROTOBUF_UNLOCK_ARMAMENT] = new UnlockArmamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_OPEN_CONTAINER] = new OpenContainerCommand();
         _loc3_[Constants_SFS.PROTOBUF_ADD_ARMAMENT] = new AddArmamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_GET_ARMAMENT_PRESET_STATUS] = new GetArmamentPresetStatusCommand();
         _loc3_[Constants_SFS.PROTOBUF_SET_ACTIVE_ARMAMENT] = new SetActiveArmamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_BUY_ITEM] = new BuyItemCommand();
         _loc3_[Constants_SFS.PROTOBUF_CLEAR_SAFE] = new ClearSafeCommand();
         _loc3_[Constants_SFS.PROTOBUF_ORDER_ITEMS] = new OrderItemsCommand();
         _loc3_[Constants_SFS.PROTOBUF_SAVE_ITEM] = new SaveItemCommand();
         _loc3_[Constants_SFS.PROTOBUF_SELL_ITEM] = new SellItemCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_ITEMS] = new ViewItemsCommand();
         _loc3_[Constants_SFS.PROTOBUF_BUY_MISSION_BOOSTER] = new BuyMissionBoosterCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_MISSION_BOOSTER] = new ShowMissionBoosterCommand();
         _loc3_[Constants_SFS.PROTOBUF_GET_PLAYER_BOOSTER] = new GetPlayerBoosterCommand();
         _loc3_[Constants_SFS.PROTOBUF_UNLOCK_INVENTORY] = new UnlockInventoryCommand();
         _loc3_[Constants_SFS.PROTOBUF_SPECIALCALENDAR] = new SpecialCalendarCommand();
         _loc3_[Constants_SFS.PROTOBUF_SPECIALWANTED] = new SpecialWantedCommand();
         _loc3_[Constants_SFS.PROTOBUF_TOURNAMENT] = new TournamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_POLICE_BADGE_CONVERSION] = new PoliceBadgeConversionCommand();
         _loc3_[Constants_SFS.PROTOBUF_LUCKY_DEVIL] = new LuckyDevilCommand();
         _loc3_[Constants_SFS.PROTOBUF_LUCKY_DEVIL_TURN_CARD] = new TurnCardCommand();
         _loc3_[Constants_SFS.PROTOBUF_LUCKY_DEVIL_BUY_CARDS] = new BuyCardsCommand();
         _loc3_[Constants_SFS.PROTOBUF_CITY_EVENT] = new CityEventStateCommand();
         _loc3_[Constants_SFS.PROTOBUF_CITY_EVENT_PROGRESS] = new CityEventProgressCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_CITY_EVENT_MISSION] = new StartCityEventMissionCommand();
         _loc3_[Constants_SFS.PROTOBUF_QUIT_CITY_EVENT_MISSION] = new QuitCityEventMissionCommand();
         _loc3_[Constants_SFS.PROTOBUF_PAY_CITY_EVENT_MISSION_COOLDOWN] = new PayCityEventMissionCooldownCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_CITY_EVENT_OPPONENTS] = new ShowCityEventOpponentCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_CITY_EVENT_FIGHT] = new StartCityEventFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_CALENDAR_UNLOCK_NEXT_DAY] = new UnlockNextDayCommand();
         _loc3_[Constants_SFS.PROTOBUF_REGISTER_FOR_TOURNAMENT] = new RegisterForTournamentCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_TOURNAMENT_FIGHT] = new ViewTournamentFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_HEAL_TOUNAMENT_PLAYER] = new HealTournamentPlayerCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_REMAINING_TOURNAMENT_PLAYERS] = new ShowRemainingTournamentPlayersCommand();
         _loc3_[Constants_SFS.PROTOBUF_SEARCH_TOURNAMENT_PLAYER] = new SearchTournamentPlayerCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_TOURNAMENT_FINALS_OVERVIEW] = new ShowTournamentFinalsCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_TOURNAMENT_INFOS] = new ShowTournamentInfoCommand();
         _loc3_[Constants_SFS.PROTOBUF_TOURNAMENT_ROUND_REPORT] = new TournamentRoundReportsCommand();
         _loc3_[Constants_SFS.PROTOBUF_POLICE_ENCOUNTER] = new PoliceEncounterCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_POLICE_FIGHT] = new StartPoliceFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_PLAYER_CURRENCY] = new PlayerCurrencyCommand();
         _loc3_[Constants_SFS.PROTOBUF_PAYMENT_INFO] = new PaymentInfoCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_CLAN] = new ShowClanCommand();
         _loc3_[Constants_SFS.PROTOBUF_GET_AVAILABLE_FAMILY_CREST_PARTS] = new GetAvailableFamilyCrestPartsCommand();
         _loc3_[Constants_SFS.PROTOBUF_CHANGE_FAMILY_CREST] = new ChangeCrestCommand();
         _loc3_[Constants_SFS.PROTOBUF_CHANGE_BULLETIN_BOARD] = new FamilyChangeBulletinBoardCommand();
         _loc3_[Constants_SFS.PROTOBUF_GET_BULLETIN_BOARD] = new FamilyGetBulletinBoardCommand();
         _loc3_[Constants_SFS.PROTOBUF_PARTICIPATE_CLAN_WAR] = new ParticipateClanWarCommand();
         _loc3_[Constants_SFS.PROTOBUF_INITIATE_CLAN_WAR] = new InitiateClanWarCommand();
         _loc3_[Constants_SFS.PROTOBUF_INVITE_PLAYER_TO_FAMILY] = new InvitePlayerToFamilyCommand();
         _loc3_[Constants_SFS.PROTOBUF_JOIN_FAMILY] = new JoinFamilyCommand();
         _loc3_[Constants_SFS.PROTOBUF_LOOKING_FOR_FAMILY] = new LookingForFamilyCommand();
         _loc3_[Constants_SFS.PROTOBUF_UPDATE_FAMILY_BONUS] = new UpdateClanBonusCommand();
         _loc3_[Constants_SFS.PROTOBUF_CREATE_FAMILY] = new CreateFamilyCommand();
         _loc3_[Constants_SFS.PROTOBUF_DONATE_FAMILY] = new DonateFamilyCommand();
         _loc3_[Constants_SFS.PROTOBUF_CHANGE_FAMILY_MEMBER_STATUS] = new ChangeFamilyMemberStatusCommand();
         _loc3_[Constants_SFS.PROTOBUF_FAMILY_MESSAGE] = new FamilyMessageCommand();
         _loc3_[Constants_SFS.PROTOBUF_RANKING_SEARCH] = new SearchRankingCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_QUEST] = new StartQuestCommand();
         _loc3_[Constants_SFS.PROTOBUF_PAUSE_QUEST] = new PauseQuestCommand();
         _loc3_[Constants_SFS.PROTOBUF_FINISH_QUEST] = new FinishQuestCommand();
         _loc3_[Constants_SFS.PROTOBUF_GET_ACTIVE_QUESTS] = new GetActiveQuestsCommand();
         _loc3_[Constants_SFS.PROTOBUF_UPDATE_QUEST] = new UpdateQuestCommand();
         _loc3_[Constants_SFS.PROTOBUF_VIEW_QUEST_BOOK] = new ViewQuestBookCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_GANGWARS] = new ShowGangWarsCommand();
         _loc3_[Constants_SFS.PROTOBUF_SELECT_CITY_FIGHT_ITEM] = new SelectCityFightItemCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_CITY_FIGHT_ITEMS] = new ShowCityFightItemsCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_CITY_FIGHT] = new StartCityFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_CITY_FIGHT] = new ShowCityFightCommand();
         _loc3_[Constants_SFS.PROTOBUF_GET_FEATURE_STATUS] = new GetFeatureStatus();
         _loc3_[Constants_SFS.PROTOBUF_SHOW_TRAVEL_POSSIBILITIES] = new ShowTravelPossibilitiesCommand();
         _loc3_[Constants_SFS.PROTOBUF_START_TRAVEL_FLIGHT] = new StartTravelFlightCommand();
         _loc3_[Constants_SFS.PROTOBUF_QUIT_TRAVEL_FLIGHT] = new QuitTravelFlightCommand();
      }
   }
}
